import type { Product } from "@/components/product-card"
import type { BlogPost } from "@/components/blog-card"

export const dummyProducts: Product[] = [
  {
    id: "1",
    name: "Monstera Deliciosa",
    description: "The Swiss Cheese Plant, known for its iconic split leaves and tropical vibes.",
    price: 39.99,
    image: "/placeholder.svg?height=400&width=400",
    category: "indoor",
    stock: 15,
    featured: true,
  },
  {
    id: "2",
    name: "Fiddle Leaf Fig",
    description: "A popular indoor tree with large, violin-shaped leaves that can grow up to 10 feet tall.",
    price: 49.99,
    image: "/placeholder.svg?height=400&width=400",
    category: "indoor",
    stock: 8,
    featured: true,
  },
  {
    id: "3",
    name: "Snake Plant",
    description: "An easy-care, drought-tolerant plant with stiff, upright leaves.",
    price: 29.99,
    image: "/placeholder.svg?height=400&width=400",
    category: "indoor",
    stock: 20,
    featured: false,
    sale: true,
    salePrice: 24.99,
  },
  {
    id: "4",
    name: "ZZ Plant",
    description: "A hardy plant with glossy, dark green leaves that can tolerate low light and neglect.",
    price: 34.99,
    image: "/placeholder.svg?height=400&width=400",
    category: "indoor",
    stock: 12,
    featured: false,
  },
  {
    id: "5",
    name: "Pothos",
    description: "A trailing vine with heart-shaped leaves, perfect for hanging baskets or shelves.",
    price: 19.99,
    image: "/placeholder.svg?height=400&width=400",
    category: "indoor",
    stock: 25,
    featured: true,
  },
  {
    id: "6",
    name: "Peace Lily",
    description: "An elegant plant with glossy leaves and white flowers, known for its air-purifying qualities.",
    price: 29.99,
    image: "/placeholder.svg?height=400&width=400",
    category: "indoor",
    stock: 10,
    featured: false,
  },
  {
    id: "7",
    name: "Aloe Vera",
    description: "A succulent with healing properties, perfect for sunny windowsills.",
    price: 15.99,
    image: "/placeholder.svg?height=400&width=400",
    category: "succulents",
    stock: 30,
    featured: false,
    sale: true,
    salePrice: 12.99,
  },
  {
    id: "8",
    name: "Rubber Plant",
    description: "A popular houseplant with large, glossy leaves that can grow into a statement tree.",
    price: 45.99,
    image: "/placeholder.svg?height=400&width=400",
    category: "indoor",
    stock: 7,
    featured: true,
  },
  {
    id: "9",
    name: "Lavender",
    description: "A fragrant herb with purple flowers, perfect for gardens and containers.",
    price: 12.99,
    image: "/placeholder.svg?height=400&width=400",
    category: "outdoor",
    stock: 40,
    featured: false,
  },
  {
    id: "10",
    name: "Japanese Maple",
    description: "A small ornamental tree with stunning red foliage, perfect for adding color to your garden.",
    price: 89.99,
    image: "/placeholder.svg?height=400&width=400",
    category: "outdoor",
    stock: 5,
    featured: true,
  },
  {
    id: "11",
    name: "Echeveria",
    description: "A rosette-forming succulent with colorful, fleshy leaves.",
    price: 9.99,
    image: "/placeholder.svg?height=400&width=400",
    category: "succulents",
    stock: 35,
    featured: false,
  },
  {
    id: "12",
    name: "Bird of Paradise",
    description: "A tropical plant with large, banana-like leaves and striking orange flowers.",
    price: 59.99,
    image: "/placeholder.svg?height=400&width=400",
    category: "indoor",
    stock: 6,
    featured: true,
    sale: true,
    salePrice: 49.99,
  },
]

export const dummyBlogPosts: BlogPost[] = [
  {
    id: "1",
    title: "10 Tips for Caring for Indoor Plants",
    excerpt: "Learn how to keep your indoor plants thriving with these essential care tips.",
    content:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed euismod, nisl vel ultricies lacinia, nisl nisl aliquam nisl, eu aliquam nisl nisl eu nisl. Sed euismod, nisl vel ultricies lacinia, nisl nisl aliquam nisl, eu aliquam nisl nisl eu nisl.",
    image: "/placeholder.svg?height=400&width=800",
    author: "Jane Smith",
    date: "2023-05-15",
    slug: "10-tips-for-caring-for-indoor-plants",
  },
  {
    id: "2",
    title: "How to Repot Your Plants: A Step-by-Step Guide",
    excerpt: "Everything you need to know about repotting your plants for optimal growth.",
    content:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed euismod, nisl vel ultricies lacinia, nisl nisl aliquam nisl, eu aliquam nisl nisl eu nisl. Sed euismod, nisl vel ultricies lacinia, nisl nisl aliquam nisl, eu aliquam nisl nisl eu nisl.",
    image: "/placeholder.svg?height=400&width=800",
    author: "John Doe",
    date: "2023-06-22",
    slug: "how-to-repot-your-plants",
  },
  {
    id: "3",
    title: "The Best Low-Maintenance Plants for Busy People",
    excerpt: "Discover plants that thrive on neglect, perfect for those with busy lifestyles.",
    content:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed euismod, nisl vel ultricies lacinia, nisl nisl aliquam nisl, eu aliquam nisl nisl eu nisl. Sed euismod, nisl vel ultricies lacinia, nisl nisl aliquam nisl, eu aliquam nisl nisl eu nisl.",
    image: "/placeholder.svg?height=400&width=800",
    author: "Sarah Johnson",
    date: "2023-07-10",
    slug: "low-maintenance-plants-for-busy-people",
  },
]
